export const actionTypes = {
  INPUT: "INPUT",
  ADD_ACADEMIC: "ADD_ACADEMIC",
  REMOVE_ARRAY_INPUT: "REMOVE_ARRAY_INPUT",
  ARRAY_INPUT: "ARRAY_INPUT",
  ADD_TRAINING: "ADD_TRAINING",
  ADD_CHILDREN: "ADD_CHILDREN",
  EDIT_FORM: "EDIT_FORM",
  BLANK_FORM: "BLANK_FORM",
};
