
export const subdivision = {
  'Dhaka North': [
    {id: 'Gulshan-0101', name: 'Gulshan-0101'},
    {id: 'Tongi-0102', name: 'Tongi-0102'},
    {id: 'Gazipur-0103', name: 'Gazipur-0103'},
    {id: 'Mymensing-0104', name: 'Mymensing-0104'},
    {id: 'Kishorgonj-0105', name: 'Kishorgonj-0105'},
    {id: 'Netrokona-0106', name: 'Netrokona-0106'},
    {id: 'Sherpur-0107', name: 'Sherpur-0107'},
  ],
  'Dhaka South': [
    {id: 'Dhanmondi-0201', name: 'Dhanmondi-0201'},
    {id: 'Motijheel-0202', name: 'Motijheel-0202'},
    {id: 'Tejgaon-0203', name: 'Tejgaon-0203'},
    {id: 'Narayangonj-0204', name: 'Narayangonj-0204'},
    {id: 'Kotwali-0205', name: 'Kotwali-0205'},
    {id: 'Lalbag-0206', name: 'Lalbag-0206'},
    {id: 'Munshigonj-0207', name: 'Munshigonj-0207'},
    {id: 'Segunbaghica-0208', name: 'Segunbaghica-0208'},
  ],
  'Dhaka East': [
    {id: 'Sutrapur-0301', name: 'Sutrapur-0301'},
    {id: 'Bondar-0302', name: 'Bondar-0302'},
    {id: 'Rupgonj-0303', name: 'Rupgonj-0303'},
    {id: 'Sonargaon-0304', name: 'Sonargaon-0304'},
    {id: 'Siddirgonj-0305', name: 'Siddirgonj-0305'},
    {id: 'Narsingdi-0306', name: 'Narsingdi-0306'},
    {id: 'Demra-0307', name: 'Demra-0307'},
    {id: 'Shampur-0308', name: 'Shampur-0308'},
  ],
  'Dhaka West': [
    {id: 'Mirpur-0401', name: 'Mirpur-0401'},
    {id: 'Mohammadpur-0402', name: 'Mohammadpur-0402'},
    {id: 'Savar-0403', name: 'Savar-0403'},
    {id: 'Dhamrai-0404', name: 'Dhamrai-0404'},
    {id: 'Manikgonj-0405', name: 'Manikgonj-0405'},
    {id: 'Tangail-0406', name: 'Tangail-0406'},
    {id: 'Jamalpur-0407', name: 'Jamalpur-0407'},
  ],
  Chattogram: [
    {id: 'Bandarban-0501', name: 'Bandarban-0501'},
    {id: 'Patiya-0502', name: 'Patiya-0502'},
    {id: 'Agrabad-0503', name: 'Agrabad-0503'},
    {id: 'Chandgaon-0504', name: 'Chandgaon-0504'},
    {id: 'Chattala-0505', name: 'Chattala-0505'},
    {id: 'Rangamati-0506', name: 'Rangamati-0506'},
    {id: "Cox's Bazar-0507", name: "Cox's Bazar-0507"},
    {id: 'Khagrachori-0508', name: 'Khagrachori-0508'},
  ],
};

export const circleData = {
  'Gulshan-0101': [
    {id: 'Circle-1', name: 'Circle-1'},
    {id: 'Circle-2', name: 'Circle-2'},
    {id: 'Circle-3', name: 'Circle-3'},
    {id: 'Circle-4', name: 'Circle-4'},
    {id: 'Circle-5', name: 'Circle-5'},
  ],
  'Tongi-0102': [
    {id: 'Circle-1', name: 'Circle-1'},
    {id: 'Circle-2', name: 'Circle-2'},
    {id: 'Circle-3', name: 'Circle-3'},
    {id: 'Circle-4', name: 'Circle-4'},
    {id: 'Circle-5', name: 'Circle-5'},
  ],
  'Gazipur-0103': [
    {id: 'Circle-1', name: 'Circle-1'},
    {id: 'Circle-2', name: 'Circle-2'},
    {id: 'Circle-3', name: 'Circle-3'},
    {id: 'Circle-4', name: 'Circle-4'},
    {id: 'Circle-5', name: 'Circle-5'},
  ],
  'Mymensing-0104': [
    {id: 'Circle-1', name: 'Circle-1'},
    {id: 'Circle-2', name: 'Circle-2'},
    {id: 'Circle-3', name: 'Circle-3'},
    {id: 'Circle-4', name: 'Circle-4'},
    {id: 'Circle-5', name: 'Circle-5'},
  ],
  'Kishorgonj-0105': [
    {id: 'Circle-1', name: 'Circle-1'},
    {id: 'Circle-2', name: 'Circle-2'},
    {id: 'Circle-3', name: 'Circle-3'},
    {id: 'Circle-4', name: 'Circle-4'},
    {id: 'Circle-5', name: 'Circle-5'},
  ],
  'Netrokona-0106': [
    {id: 'Circle-1', name: 'Circle-1'},
    {id: 'Circle-2', name: 'Circle-2'},
    {id: 'Circle-3', name: 'Circle-3'},
    {id: 'Circle-4', name: 'Circle-4'},
    {id: 'Circle-5', name: 'Circle-5'},
  ],
  'Sherpur-0107': [
    {id: 'Circle-1', name: 'Circle-1'},
    {id: 'Circle-2', name: 'Circle-2'},
    {id: 'Circle-3', name: 'Circle-3'},
    {id: 'Circle-4', name: 'Circle-4'},
    {id: 'Circle-5', name: 'Circle-5'},
  ],
  'Dhanmondi-0201': [
    {id: 'Dhanmondi', name: 'Dhanmondi'},
    {id: 'Rayerbazar', name: 'Rayerbazar'},
    {id: 'Kalabagan', name: 'Kalabagan'},
    {id: 'Nilkhet', name: 'Nilkhet'},
  ],
  'Motijheel-0202': [
    {id: 'Motijheel', name: 'Motijheel'},
    {id: 'Razarbag', name: 'Razarbag'},
    {id: 'Arambag', name: 'Arambag'},
    {id: 'Rampura', name: 'Rampura'},
  ],
  'Tejgaon-0203': [
    {id: 'Tejgaon', name: 'Tejgaon'},
    {id: 'Begunbari', name: 'Begunbari'},
    {id: 'Kawranbazar', name: 'Kawranbazar'},
    {id: 'Firmgate', name: 'Firmgate'},
  ],
  'Narayangonj-0204': [
    {id: 'Narayangonj', name: 'Narayangonj'},
    {id: 'Fatullah', name: 'Fatullah'},
    {id: 'Aliganj', name: 'Aliganj'},
    {id: 'Enayet Nagar', name: 'Enayet Nagar'},
  ],
  'Kotwali-0205': [
    {id: 'Bongshal', name: 'Bongshal'},
    {id: 'Armanitola', name: 'Armanitola'},
    {id: 'Chawkbazar', name: 'Chawkbazar'},
    {id: 'Bakshi Bazar', name: 'Bakshi Bazar'},
  ],
  'Lalbag-0206': [
    {id: 'Azimpur', name: 'Azimpur'},
    {id: 'Imamgonj', name: 'Imamgonj'},
    {id: 'Keranigonj', name: 'Keranigonj'},
    {id: 'Hasnabad', name: 'Hasnabad'},
  ],
  'Munshigonj-0207': [
    {id: 'Munshigonj', name: 'Munshigonj'},
    {id: 'Gojaria', name: 'Gojaria'},
    {id: 'Srinagar', name: 'Srinagar'},
    {id: 'Sirajdikhan', name: 'Sirajdikhan'},
  ],
  'Segunbaghica-0208': [
    {id: 'Segunbaghica', name: 'Segunbaghica'},
    {id: 'Siddeshwari', name: 'Siddeshwari'},
    {id: 'Fulbaria', name: 'Fulbaria'},
    {id: 'Palton', name: 'Palton'},
  ],
  'Sutrapur-0301': [
    {id: 'Gandaria', name: 'Gandaria'},
    {id: 'Mirhazaribag', name: 'Mirhazaribag'},
    {id: 'Postugola', name: 'Postugola'},
    {id: 'Sutrapur', name: 'Sutrapur'},
  ],
  'Bondar-0302': [
    {id: 'Bondar', name: 'Bondar'},
    {id: 'Kachpur', name: 'Kachpur'},
    {id: 'Dhamgarh', name: 'Dhamgarh'},
    {id: 'Shimrail', name: 'Shimrail'},
  ],
  'Rupgonj-0303': [
    {id: 'Rupgonj', name: 'Rupgonj'},
    {id: 'Tarabo', name: 'Tarabo'},
    {id: 'Vulta', name: 'Vulta'},
    {id: 'Murapara', name: 'Murapara'},
  ],
  'Sonargaon-0304': [
    {id: 'Sonargaon', name: 'Sonargaon'},
    {id: 'Madanpur', name: 'Madanpur'},
    {id: 'Mugrapara', name: 'Mugrapara'},
    {id: 'Araihajar', name: 'Araihajar'},
  ],
  'Siddirgonj-0305': [
    {id: 'Siddirgonj', name: 'Siddirgonj'},
    {id: 'Hirajhil', name: 'Hirajhil'},
    {id: 'Mouchak', name: 'Mouchak'},
    {id: 'Jalcuri', name: 'Jalcuri'},
  ],
  'Narsingdi-0306': [
    {id: 'Narsingdi', name: 'Narsingdi'},
    {id: 'Sibpur', name: 'Sibpur'},
    {id: 'Ghorasal', name: 'Ghorasal'},
    {id: 'Bhairab', name: 'Bhairab'},
  ],
  'Demra-0307': [
    {id: 'Demra', name: 'Demra'},
    {id: 'Rayerbag', name: 'Rayerbag'},
    {id: 'Tikatuli', name: 'Tikatuli'},
    {id: 'Konapara', name: 'Konapara'},
  ],
  'Shampur-0308': [
    {id: 'Shampur', name: 'Shampur'},
    {id: 'Dania', name: 'Dania'},
    {id: 'Dhaleshar', name: 'Dhaleshar'},
    {id: 'Kadamtali', name: 'Kadamtali'},
  ],
  'Mirpur-0401': [
    {id: 'Pollabi Circle-1', name: 'Pollabi Circle-1'},
    {id: 'Pollabi Circle-2', name: 'Pollabi Circle-2'},
    {id: 'Kazipara', name: 'Kazipara'},
    {id: 'Kafrul', name: 'Kafrul'},
    {id: 'Kallyanpur', name: 'Kallyanpur'},
  ],
  'Mohammadpur-0402': [
    {id: 'Mohammadpur', name: 'Mohammadpur'},
    {id: 'Razabazar', name: 'Razabazar'},
    {id: 'Shyamoli', name: 'Shyamoli'},
  ],
  'Savar-0403': [
    {id: 'Hemayatpur', name: 'Hemayatpur'},
    {id: 'Savar', name: 'Savar'},
    {id: 'Dhamsona', name: 'Dhamsona'},
    {id: 'Rajashon', name: 'Rajashon'},
    {id: 'Ashulia', name: 'Ashulia'},
  ],
  'Dhamrai-0404': [
    {id: 'Dhamrai', name: 'Dhamrai'},
    {id: 'Singair', name: 'Singair'},
  ],
  'Manikgonj-0405': [
    {id: 'Manikgonj', name: 'Manikgonj'},
    {id: 'Shibaloy', name: 'Shibaloy'},
  ],
  'Tangail-0406': [
    {id: 'Circle-1', name: 'Circle-1'},
    {id: 'Circle-2', name: 'Circle-2'},
    {id: 'Circle-3', name: 'Circle-3'},
  ],
  'Jamalpur-0407': [
    {id: 'Circle-1', name: 'Circle-1'},
    {id: 'Circle-2', name: 'Circle-2'},
  ],
  'Bandarban-0501': [
    {id: 'Bandarban', name: 'Bandarban'},
    {id: 'Lama', name: 'Lama'},
  ],
  'Patiya-0502': [
    {id: 'Patiya', name: 'Patiya'},
    {id: 'Karnafuly', name: 'Karnafuly'},
    {id: 'Boalkhali', name: 'Boalkhali'},
  ],
  'Agrabad-0503': [
    {id: 'Agrabad', name: 'Agrabad'},
    {id: 'Potenga', name: 'Potenga'},
    {id: 'Sadarghat', name: 'Sadarghat'},
    {id: 'Kotwali', name: 'Kotwali'},
  ],
  'Chandgaon-0504': [
    {id: 'Bakolia', name: 'Bakolia'},
    {id: 'Kalurghat', name: 'Kalurghat'},
    {id: 'Kaptai', name: 'Kaptai'},
    {id: 'Nasirabad', name: 'Nasirabad'},
  ],
  'Chattala-0505': [
    {id: 'Halishahar', name: 'Halishahar'},
    {id: 'Pahartali', name: 'Pahartali'},
    {id: 'Foujdarhat', name: 'Foujdarhat'},
    {id: 'Panchlaish', name: 'Panchlaish'},
  ],
  'Rangamati-0506': [
    {id: 'Rangamati', name: 'Rangamati'},
    {id: 'Rangunia', name: 'Rangunia'},
  ],
  "Cox's Bazar-0507": [
    {id: "Cox's Bazar", name: "Cox's Bazar"},
    {id: 'Chakaria', name: 'Chakaria'},
    {id: 'Teknaf', name: 'Teknaf'},
  ],
  'Khagrachori-0508': [
    {id: 'Khagrachori', name: 'Khagrachori'},
    {id: 'Sitakunda', name: 'Sitakunda'},
  ],
};
